### ISSUE TITLE
Add  config and logic to allow router traffic by service Id in the header

### ISSUE THREAD

**Issue by GavinChenYan** [networknt/http-sidecar#2]
Allow allow router traffic by service Id

And the router traffic will be optional by service Id or protocol type

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add config and logic to allow router traffic by service Id in the header http-sidecar master](https://trello.com/c/1Fade3MJ/1135-add-config-and-logic-to-allow-router-traffic-by-service-id-in-the-header-http-sidecar-master)
